/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeDemo */

#ifndef _Included_NativeDemo
#define _Included_NativeDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeDemo
 * Method:    factorial
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_NativeDemo_factorial
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
